services:
  openrouter-proxy:
    container_name: openrouter-proxy
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json  # Mount config file so changes persist
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN} --url http://openrouter-proxy:5000
    env_file:
      - .env
    restart: unless-stopped